// <auto-generated />
using HomeHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeHub.Api.Migrations
{
    [DbContext(typeof(HomeHubDbContext))]
    [Migration("20260720115852_Stage1_ProfilesAndSettings")]
    partial class Stage1_ProfilesAndSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeHub.Api.Profiles.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Initial")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PinHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("RequirePinWhenIdle")
                        .HasColumnType("bit");

                    b.Property<bool>("StayLoggedIn")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 0,
                            Initial = "A",
                            Name = "Astrid",
                            RequirePinWhenIdle = false,
                            StayLoggedIn = true
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 1,
                            Initial = "R",
                            Name = "Ragnar",
                            RequirePinWhenIdle = false,
                            StayLoggedIn = true
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 2,
                            Initial = "L",
                            Name = "Leif",
                            RequirePinWhenIdle = false,
                            StayLoggedIn = true
                        });
                });

            modelBuilder.Entity("HomeHub.Api.Settings.HouseholdSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActiveProfileId")
                        .HasColumnType("int");

                    b.Property<int>("FreezerWarnAboveCelsius")
                        .HasColumnType("int");

                    b.Property<int>("HumidityWarnAbovePercent")
                        .HasColumnType("int");

                    b.Property<bool>("IdleDimmingEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("IdleTimeoutMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FreezerWarnAboveCelsius = 10,
                            HumidityWarnAbovePercent = 65,
                            IdleDimmingEnabled = true,
                            IdleTimeoutMinutes = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
