// <auto-generated />
using System;
using HomeHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeHub.Api.Migrations
{
    [DbContext(typeof(HomeHubDbContext))]
    [Migration("20260720152521_Stage4_Calendar")]
    partial class Stage4_Calendar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeHub.Api.Alerts.ActiveAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClearedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Type", "ClearedAtUtc");

                    b.ToTable("ActiveAlerts");
                });

            modelBuilder.Entity("HomeHub.Api.Alerts.AlertThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int>("Metric")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("AlertThresholds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direction = 0,
                            DurationMinutes = 10,
                            Enabled = true,
                            Metric = 0,
                            Severity = 2,
                            Value = 10.0,
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 2,
                            Direction = 0,
                            DurationMinutes = 10,
                            Enabled = true,
                            Metric = 0,
                            Severity = 1,
                            Value = 40.0,
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 3,
                            Direction = 0,
                            DurationMinutes = 10,
                            Enabled = true,
                            Metric = 1,
                            Severity = 1,
                            Value = 65.0,
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 4,
                            Direction = 0,
                            DurationMinutes = 10,
                            Enabled = true,
                            Metric = 1,
                            Severity = 1,
                            Value = 65.0,
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 5,
                            Direction = 0,
                            DurationMinutes = 10,
                            Enabled = true,
                            Metric = 1,
                            Severity = 1,
                            Value = 65.0,
                            ZoneId = 5
                        });
                });

            modelBuilder.Entity("HomeHub.Api.Calendar.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OwnerTags")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GoogleId");

                    b.HasIndex("StartUtc");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("HomeHub.Api.Profiles.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Initial")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PinHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("RequirePinWhenIdle")
                        .HasColumnType("bit");

                    b.Property<bool>("StayLoggedIn")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 0,
                            Initial = "A",
                            Name = "Astrid",
                            RequirePinWhenIdle = false,
                            StayLoggedIn = true
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 1,
                            Initial = "R",
                            Name = "Ragnar",
                            RequirePinWhenIdle = false,
                            StayLoggedIn = true
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 2,
                            Initial = "L",
                            Name = "Leif",
                            RequirePinWhenIdle = false,
                            StayLoggedIn = true
                        });
                });

            modelBuilder.Entity("HomeHub.Api.Sensors.SensorReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Humidity")
                        .HasColumnType("float");

                    b.Property<double>("TempF")
                        .HasColumnType("float");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId", "TimestampUtc");

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("HomeHub.Api.Sensors.SensorZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ProviderRef")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Source", "ProviderRef")
                        .IsUnique();

                    b.ToTable("SensorZones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            DisplayOrder = 0,
                            Name = "Freezer",
                            ProviderRef = "sim-freezer",
                            Source = "simulated"
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            DisplayOrder = 1,
                            Name = "Fridge",
                            ProviderRef = "sim-fridge",
                            Source = "simulated"
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            DisplayOrder = 2,
                            Name = "Living Room",
                            ProviderRef = "sim-living",
                            Source = "simulated"
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            DisplayOrder = 3,
                            Name = "Kitchen",
                            ProviderRef = "sim-kitchen",
                            Source = "simulated"
                        },
                        new
                        {
                            Id = 5,
                            Category = 0,
                            DisplayOrder = 4,
                            Name = "Bedroom",
                            ProviderRef = "sim-bedroom",
                            Source = "simulated"
                        });
                });

            modelBuilder.Entity("HomeHub.Api.Settings.HouseholdSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActiveProfileId")
                        .HasColumnType("int");

                    b.Property<bool>("IdleDimmingEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("IdleTimeoutMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdleDimmingEnabled = true,
                            IdleTimeoutMinutes = 5
                        });
                });

            modelBuilder.Entity("HomeHub.Api.Weather.WeatherCache", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WeatherCache");
                });

            modelBuilder.Entity("HomeHub.Api.Alerts.AlertThreshold", b =>
                {
                    b.HasOne("HomeHub.Api.Sensors.SensorZone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("HomeHub.Api.Sensors.SensorReading", b =>
                {
                    b.HasOne("HomeHub.Api.Sensors.SensorZone", "Zone")
                        .WithMany("Readings")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("HomeHub.Api.Sensors.SensorZone", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
