// <auto-generated />
using System;
using HomeHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeHub.Api.Migrations
{
    [DbContext(typeof(HomeHubDbContext))]
    partial class HomeHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeHub.Api.Alerts.ActiveAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClearedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Type", "ClearedAtUtc");

                    b.ToTable("ActiveAlerts");
                });

            modelBuilder.Entity("HomeHub.Api.Alerts.AlertThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int>("Metric")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("AlertThresholds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direction = 0,
                            DurationMinutes = 10,
                            Enabled = true,
                            Metric = 0,
                            Severity = 2,
                            Value = 10.0,
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 2,
                            Direction = 0,
                            DurationMinutes = 10,
                            Enabled = true,
                            Metric = 0,
                            Severity = 1,
                            Value = 40.0,
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 3,
                            Direction = 0,
                            DurationMinutes = 10,
                            Enabled = true,
                            Metric = 1,
                            Severity = 1,
                            Value = 65.0,
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 4,
                            Direction = 0,
                            DurationMinutes = 10,
                            Enabled = true,
                            Metric = 1,
                            Severity = 1,
                            Value = 65.0,
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 5,
                            Direction = 0,
                            DurationMinutes = 10,
                            Enabled = true,
                            Metric = 1,
                            Severity = 1,
                            Value = 65.0,
                            ZoneId = 5
                        });
                });

            modelBuilder.Entity("HomeHub.Api.Calendar.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CalendarName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoogleBirthdayType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleCalendarId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GoogleEventType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Mark")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OwnerTags")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GoogleId");

                    b.HasIndex("StartUtc");

                    b.HasIndex("ProfileId", "StartUtc");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("HomeHub.Api.Calendar.GoogleAccountLink", b =>
                {
                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<bool>("CalendarsConfigured")
                        .HasColumnType("bit");

                    b.Property<string>("PrimaryCalendarId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfileId");

                    b.ToTable("GoogleAccountLinks");
                });

            modelBuilder.Entity("HomeHub.Api.Calendar.SyncedCalendar", b =>
                {
                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("GoogleCalendarId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CalendarName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfileId", "GoogleCalendarId");

                    b.ToTable("SyncedCalendars");
                });

            modelBuilder.Entity("HomeHub.Api.Cats.LitterRobotRecovery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FaultCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Manual")
                        .HasColumnType("bit");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<string>("ResultingCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Step")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug", "StartedAtUtc");

                    b.ToTable("LitterRobotRecoveries");
                });

            modelBuilder.Entity("HomeHub.Api.Climate.ClimateZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CurrentTempF")
                        .HasColumnType("float");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FanMode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ProviderRef")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<double>("SetPointF")
                        .HasColumnType("float");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Source", "ProviderRef")
                        .IsUnique();

                    b.ToTable("ClimateZones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentTempF = 74.0,
                            DisplayOrder = 0,
                            FanMode = "Quiet",
                            Mode = 1,
                            Name = "Living Room",
                            ProviderRef = "sim-living",
                            SetPointF = 72.0,
                            Source = "simulated",
                            UpdatedUtc = new DateTime(1, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CurrentTempF = 71.0,
                            DisplayOrder = 1,
                            FanMode = "Auto",
                            Mode = 1,
                            Name = "Bedroom",
                            ProviderRef = "sim-bedroom",
                            SetPointF = 70.0,
                            Source = "simulated",
                            UpdatedUtc = new DateTime(1, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CurrentTempF = 73.0,
                            DisplayOrder = 2,
                            FanMode = "Auto",
                            Mode = 3,
                            Name = "Kitchen",
                            ProviderRef = "sim-kitchen",
                            SetPointF = 73.0,
                            Source = "simulated",
                            UpdatedUtc = new DateTime(1, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CurrentTempF = 72.0,
                            DisplayOrder = 3,
                            Mode = 0,
                            Name = "Study",
                            ProviderRef = "sim-study",
                            SetPointF = 72.0,
                            Source = "simulated",
                            UpdatedUtc = new DateTime(1, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CurrentTempF = 72.0,
                            DisplayOrder = 4,
                            Mode = 0,
                            Name = "Loft",
                            ProviderRef = "sim-loft",
                            SetPointF = 72.0,
                            Source = "simulated",
                            UpdatedUtc = new DateTime(1, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HomeHub.Api.Meals.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cuisine")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedByProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PrepNote")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<int?>("Servings")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived", "Name");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("HomeHub.Api.Meals.MealComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("MealId", "Position");

                    b.HasIndex("MealId", "RecipeId")
                        .IsUnique();

                    b.ToTable("MealComponents");
                });

            modelBuilder.Entity("HomeHub.Api.Meals.MealPlanEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("FreeText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("ServingsOverride")
                        .HasColumnType("int");

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<bool?>("WasEaten")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("Date", "Slot", "Position");

                    b.ToTable("MealPlanEntries");
                });

            modelBuilder.Entity("HomeHub.Api.Meals.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Completeness")
                        .HasColumnType("int");

                    b.Property<int?>("CookMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("ForkedFrom")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ImageSourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ImportMethod")
                        .HasColumnType("int");

                    b.Property<string>("IncompleteReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<int?>("LeadMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedByProfileId")
                        .HasColumnType("int");

                    b.Property<int?>("PrepMinutes")
                        .HasColumnType("int");

                    b.Property<string>("PrepNote")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<int?>("Servings")
                        .HasColumnType("int");

                    b.Property<string>("SourceName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("TotalMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("YieldText")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.HasIndex("IsArchived", "Title");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("HomeHub.Api.Meals.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("decimal(9,3)");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("SectionHeading")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Unit")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "Position");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("HomeHub.Api.Meals.RecipeStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("SectionHeading")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "Position");

                    b.ToTable("RecipeSteps");
                });

            modelBuilder.Entity("HomeHub.Api.Meals.RecipeTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Tag");

                    b.HasIndex("RecipeId", "Tag")
                        .IsUnique();

                    b.ToTable("RecipeTags");
                });

            modelBuilder.Entity("HomeHub.Api.Notifications.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accent")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Meta")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Route")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("AtUtc");

                    b.HasIndex("DedupeKey")
                        .IsUnique();

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HomeHub.Api.Notifications.NotificationSourceSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Source")
                        .IsUnique();

                    b.ToTable("NotificationSources");
                });

            modelBuilder.Entity("HomeHub.Api.Pantry.GroceryLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddedByProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CheckedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CheckedByProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MirrorPending")
                        .HasColumnType("bit");

                    b.Property<int?>("PantryItemId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("decimal(9,3)");

                    b.Property<int>("SourceKind")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TodoTaskId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Unit")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CheckedAtUtc");

                    b.HasIndex("PantryItemId");

                    b.HasIndex("TodoTaskId");

                    b.ToTable("GroceryLines");
                });

            modelBuilder.Entity("HomeHub.Api.Pantry.GroceryLineSourceRef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ByProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("ForDate")
                        .HasColumnType("date");

                    b.Property<int>("GroceryLineId")
                        .HasColumnType("int");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("RecipeTitle")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("GroceryLineId");

                    b.ToTable("GroceryLineSources");
                });

            modelBuilder.Entity("HomeHub.Api.Pantry.GroceryMirrorSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastError")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("LastSyncedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OwnerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("TodoListId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TodoListName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("GroceryMirror");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsecutiveFailures = 0
                        });
                });

            modelBuilder.Entity("HomeHub.Api.Pantry.IngredientAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Confidence")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PantryItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.HasIndex("PantryItemId");

                    b.ToTable("IngredientAliases");
                });

            modelBuilder.Entity("HomeHub.Api.Pantry.OrderImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AppliedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AppliedByProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OrderedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasMaxLength(200000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VendorLabel")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveredAtUtc");

                    b.HasIndex("Status", "CreatedUtc");

                    b.ToTable("OrderImports");
                });

            modelBuilder.Entity("HomeHub.Api.Pantry.OrderImportLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Applied")
                        .HasColumnType("bit");

                    b.Property<int>("Confidence")
                        .HasColumnType("int");

                    b.Property<decimal?>("GuessFromPounds")
                        .HasPrecision(9, 3)
                        .HasColumnType("decimal(9,3)");

                    b.Property<int>("ImportId")
                        .HasColumnType("int");

                    b.Property<int?>("MatchedPantryItemId")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("ProposedLocation")
                        .HasColumnType("int");

                    b.Property<string>("ProposedName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("ProposedQuantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("decimal(9,3)");

                    b.Property<int>("ProposedTracking")
                        .HasColumnType("int");

                    b.Property<string>("ProposedUnit")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("ImportId", "Position");

                    b.ToTable("OrderImportLines");
                });

            modelBuilder.Entity("HomeHub.Api.Pantry.PantryEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ByProfileId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Delta")
                        .HasPrecision(9, 3)
                        .HasColumnType("decimal(9,3)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<int>("PantryItemId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ResultingQuantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("decimal(9,3)");

                    b.Property<int?>("ResultingState")
                        .HasColumnType("int");

                    b.Property<Guid?>("ScanRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ScanSequence")
                        .HasColumnType("int");

                    b.Property<bool>("SetsAbsolute")
                        .HasColumnType("bit");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceKind")
                        .HasColumnType("int");

                    b.Property<int?>("UndoneByEventId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PantryItemId", "AtUtc");

                    b.HasIndex("ScanRunId", "ScanSequence")
                        .IsUnique()
                        .HasFilter("[ScanRunId] IS NOT NULL");

                    b.HasIndex("SourceKind", "SourceId");

                    b.ToTable("PantryEvents");
                });

            modelBuilder.Entity("HomeHub.Api.Pantry.PantryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CatalogueRef")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EstimateState")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("decimal(9,3)");

                    b.Property<int>("Tracking")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CatalogueRef");

                    b.HasIndex("IsArchived", "Location", "Name");

                    b.ToTable("PantryItems");
                });

            modelBuilder.Entity("HomeHub.Api.Pantry.ProductCatalogueEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefaultLocation")
                        .HasColumnType("int");

                    b.Property<int>("DefaultTracking")
                        .HasColumnType("int");

                    b.Property<string>("DefaultUnit")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("PackSize")
                        .HasPrecision(9, 3)
                        .HasColumnType("decimal(9,3)");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Barcode", "Scope")
                        .IsUnique();

                    b.ToTable("ProductCatalogue");
                });

            modelBuilder.Entity("HomeHub.Api.Pantry.StockCheckDismissal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ByProfileId")
                        .HasColumnType("int");

                    b.Property<int>("PlanEntryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanEntryId")
                        .IsUnique();

                    b.ToTable("StockCheckDismissals");
                });

            modelBuilder.Entity("HomeHub.Api.Profiles.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Initial")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PinHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("RequirePinWhenIdle")
                        .HasColumnType("bit");

                    b.Property<bool>("StayLoggedIn")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 0,
                            Initial = "A",
                            Name = "Astrid",
                            RequirePinWhenIdle = false,
                            StayLoggedIn = true
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 1,
                            Initial = "R",
                            Name = "Ragnar",
                            RequirePinWhenIdle = false,
                            StayLoggedIn = true
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 2,
                            Initial = "L",
                            Name = "Leif",
                            RequirePinWhenIdle = false,
                            StayLoggedIn = true
                        });
                });

            modelBuilder.Entity("HomeHub.Api.Sensors.SensorReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Humidity")
                        .HasColumnType("float");

                    b.Property<double>("TempF")
                        .HasColumnType("float");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId", "TimestampUtc");

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("HomeHub.Api.Sensors.SensorZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ProviderRef")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Source", "ProviderRef")
                        .IsUnique();

                    b.ToTable("SensorZones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            DisplayOrder = 0,
                            Name = "Freezer",
                            ProviderRef = "sim-freezer",
                            Source = "simulated"
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            DisplayOrder = 1,
                            Name = "Fridge",
                            ProviderRef = "sim-fridge",
                            Source = "simulated"
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            DisplayOrder = 2,
                            Name = "Living Room",
                            ProviderRef = "sim-living",
                            Source = "simulated"
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            DisplayOrder = 3,
                            Name = "Kitchen",
                            ProviderRef = "sim-kitchen",
                            Source = "simulated"
                        },
                        new
                        {
                            Id = 5,
                            Category = 0,
                            DisplayOrder = 4,
                            Name = "Bedroom",
                            ProviderRef = "sim-bedroom",
                            Source = "simulated"
                        });
                });

            modelBuilder.Entity("HomeHub.Api.Settings.HouseholdSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActiveProfileId")
                        .HasColumnType("int");

                    b.Property<string>("CatName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DaylightBoost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IdleDimmingEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("IdleTimeoutMinutes")
                        .HasColumnType("int");

                    b.Property<int>("LitterFullPercent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DaylightBoost = "auto",
                            IdleDimmingEnabled = true,
                            IdleTimeoutMinutes = 5,
                            LitterFullPercent = 80
                        });
                });

            modelBuilder.Entity("HomeHub.Api.Tasks.MicrosoftAccountLink", b =>
                {
                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LinkedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ListId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("ListsConfigured")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfileId");

                    b.ToTable("MicrosoftAccountLinks");
                });

            modelBuilder.Entity("HomeHub.Api.Tasks.SyncedList", b =>
                {
                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("GraphListId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ListName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProfileId", "GraphListId");

                    b.ToTable("SyncedLists");
                });

            modelBuilder.Entity("HomeHub.Api.Tasks.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GraphId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GraphListId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Important")
                        .HasColumnType("bit");

                    b.Property<string>("ListName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GraphId");

                    b.HasIndex("ProfileId", "Completed");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("HomeHub.Api.Weather.WeatherCache", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WeatherCache");
                });

            modelBuilder.Entity("HomeHub.Api.Alerts.AlertThreshold", b =>
                {
                    b.HasOne("HomeHub.Api.Sensors.SensorZone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("HomeHub.Api.Meals.MealComponent", b =>
                {
                    b.HasOne("HomeHub.Api.Meals.Meal", "Meal")
                        .WithMany("Components")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeHub.Api.Meals.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("HomeHub.Api.Meals.MealPlanEntry", b =>
                {
                    b.HasOne("HomeHub.Api.Meals.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("HomeHub.Api.Meals.RecipeIngredient", b =>
                {
                    b.HasOne("HomeHub.Api.Meals.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("HomeHub.Api.Meals.RecipeStep", b =>
                {
                    b.HasOne("HomeHub.Api.Meals.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("HomeHub.Api.Meals.RecipeTag", b =>
                {
                    b.HasOne("HomeHub.Api.Meals.Recipe", "Recipe")
                        .WithMany("Tags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("HomeHub.Api.Pantry.GroceryLine", b =>
                {
                    b.HasOne("HomeHub.Api.Pantry.PantryItem", "Item")
                        .WithMany()
                        .HasForeignKey("PantryItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Item");
                });

            modelBuilder.Entity("HomeHub.Api.Pantry.GroceryLineSourceRef", b =>
                {
                    b.HasOne("HomeHub.Api.Pantry.GroceryLine", "Line")
                        .WithMany("Sources")
                        .HasForeignKey("GroceryLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("HomeHub.Api.Pantry.IngredientAlias", b =>
                {
                    b.HasOne("HomeHub.Api.Pantry.PantryItem", "Item")
                        .WithMany()
                        .HasForeignKey("PantryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("HomeHub.Api.Pantry.OrderImportLine", b =>
                {
                    b.HasOne("HomeHub.Api.Pantry.OrderImport", "Import")
                        .WithMany("Lines")
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Import");
                });

            modelBuilder.Entity("HomeHub.Api.Pantry.PantryEvent", b =>
                {
                    b.HasOne("HomeHub.Api.Pantry.PantryItem", "Item")
                        .WithMany("Events")
                        .HasForeignKey("PantryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("HomeHub.Api.Sensors.SensorReading", b =>
                {
                    b.HasOne("HomeHub.Api.Sensors.SensorZone", "Zone")
                        .WithMany("Readings")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("HomeHub.Api.Meals.Meal", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("HomeHub.Api.Meals.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Steps");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("HomeHub.Api.Pantry.GroceryLine", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("HomeHub.Api.Pantry.OrderImport", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("HomeHub.Api.Pantry.PantryItem", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("HomeHub.Api.Sensors.SensorZone", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
